article/urls.py
from django.contrib import admin
from django.urls import path

from . import views
app_name = "article"

urlpatterns = [
     path('dashboard/', views.dashboard, name = "dashboard"),
     path('addarticle/', views.addArticle, name = "addarticle"),
     path('article/<int:id>', views.details, name = "detail"),
     path('update/<int:id>', views.updateArticle, name = "update"),
     path('delete/<int:id>', views.deleteArticle, name = "delete"),
     path('comment/<int:id>', views.addComment, name = "comment"),
     path('', views.articles, name = "article"),

]

myBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"),
    path('about/', views.about, name = "about"),
    path('articles/',include("article.urls")),
    path('users/',include("user.urls")),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path

from . import views
app_name = "user"

urlpatterns = [
     path('login/', views.loginUser, name = "login"),
     path('register/', views.signup, name = "register"),
     path('logout/', views.logoutUser, name = "logout"),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
#Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete = models.CASCADE,verbose_name = "Yazar" )
    title = models.CharField(max_length = 50, verbose_name="Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturma Tarihi")
    article_image = models.ImageField(verbose_name="Makaleye Fotoğraf Ekleyin")
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['-created_date']


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE, verbose_name="Makale",related_name="comments")
    comment_author = models.CharField(max_length= 50,verbose_name="İsim")
    comment_content = models.CharField(max_length=200, verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content","article_image"]
        

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



#giriş formumuz
class LoginForm(forms.Form):
    username = forms.CharField(max_length=20, label = "Kullanıcı Adı")
    password = forms.CharField(max_length=20, label = "Parola", widget = forms.PasswordInput)



#kayıt olma formu
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30,help_text="Zorunludur.", label="Adınız")
    last_name = forms.CharField(max_length=30, required=False, help_text='İsteğe bağlıdır.', label= "Soyadınız")
    email = forms.EmailField(max_length=254, help_text='Geçerli bir e-mail adresi girin.') 

    class Meta:
        model = User
        fields = ('username', 'first_name' , 'last_name', 'email', 'password1', 'password2', )


class logout(forms.Form):
    pass

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.
#requestin her viewde kullanılması gerekiyor...
def index(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(content__contains = keyword)
        return render(request,"index.html", {"articles":articles})
    articles = Article.objects.all()
    return render(request, "index.html",{"articles":articles})


@login_required(login_url= "user:login")
def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(content__contains = keyword)
        return render(request,"articles.html", {"articles":articles})
    articles = Article.objects.filter(author = request.user)
    return render(request, "articles.html",{"articles":articles})



def about(request):
    return render(request, "about.html")



@login_required(login_url= "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context={
        "articles":articles
    }

    return render(request, "dashboard.html", context)



@login_required(login_url= "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)

        article.author = request.user
        article.save()

        messages.success(request,"Makale başarıyla oluşturuldu.")
        return redirect("index")

    return render(request, "addarticle.html" ,{"form":form})


def details(request, id):
    article = get_object_or_404(Article,id=id)
    
    comment = article.comments.all()
    return render(request,"detail.html", {"article":article,"comments":comment})



@login_required(login_url= "user:login")
def updateArticle(request, id):
    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None, request.FILES or None,instance = article)

    if form.is_valid():
        article = form.save(commit=False)

        article.author = request.user
        article.save()

        messages.success(request,"Makale başarıyla güncellendi.")
        return redirect("article:dashboard")

    return render(request, "update.html",{"form":form})


@login_required(login_url= "user:login")
def deleteArticle(request, id):
    article = get_object_or_404(Article, id = id)

    article.delete()

    messages.success(request,"Makale başarıyla silindi.")
    return redirect("article:dashboard")



def addComment(request,id):
    article = get_object_or_404(Article,id=id)
    
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author = comment_author,comment_content=comment_content)
        newComment.article = article

        newComment.save()

    return redirect(reverse("article:detail",kwargs={"id":id}))

user/views.py
from django.shortcuts import render,redirect
from .forms import LoginForm , SignUpForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required


@login_required
def home(request):
    return render(request, 'index.html')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = SignUpForm()
    return render(request, 'users/register.html', {'form': form})




def loginUser(request):
    
    form = LoginForm(request.POST or None)
    context = {
        "form":form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        
        user = authenticate(username = username, password = password)

        if user is None:
            messages.warning(request,"Kullanıcı adı veya parola hatalı")
            return render(request,"users/login.html",context)

        messages.success(request,"Başarıyla giriş yaptınız.")
        login(request,user)
        return redirect("index")

    return render(request,"users/login.html",context)


def logoutUser(request):
    logout(request)
    messages.info(request,"Çıkış yapıldı.")
    return redirect("index")

templates/about.html
{% extends "layout.html" %}

{% block body %}

<h3>Hakkımızda</h3>
<hr>
<div class="jumbotron text-center">
        <p>Bu blogda programlama ile ilgili derin bilgiler paylaşacağım</p>
</div>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Oluştur</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-primary">Ekle</button>
        </form>
    </div>
</div>

{% endblock body %}

templates/articles.html
{% extends "layout.html" %}
{% block body %}
                     
    
{% if articles %}

<div class="container">
    <h3>Yayınladığınız Makaleler</h3>
    <hr>
    <p>
        Hoş geldiniz, <small>{{request.user.first_name}}</small>
</p>
    <div class="" style="float:right">
                    
            <!-- Search Widget -->
            <div class="card my-4">
              <h5 class="card-header">Makale arayın</h5>
              <div class="card-body">
                    
                        <form class="input-group">
                                {% csrf_token %}
                                <input type="text" name="keyword" class="form-control" maxlength="10" placeholder="Ara...">
                                <button type="submit" class="btn btn-primary">Ara</button>
                            </form>   
                </div>
            </div>
          </div>
  
    <div class="row"> 

{% for article in articles %}
    <!-- Page Content -->
  
    
      
              <!-- Blog Entries Column -->
              <div class="col-md-12">
      
                <!-- Blog Post -->
                <div class="card mb-4">
                  <img class="card-img-top" src="{{article.article_image.url}}" alt="">
                  <div class="card-body">
                   <a href="{% url 'article:detail' article.id  %}"><h2 class="card-title">{{article.title}}</h2></a> 
                    <p class="card-text">{{article.content|safe|truncatewords:50}}</p>
                    <a href="{% url 'article:detail' article.id  %}" class="btn btn-primary" style="float:right">Devamını Oku &rarr;</a>
                  </div>
                  <div class="card-footer text-muted">
                    <p>{{article.author.username}} tarafından {{article.created_date}}'da oluşturuldu.</p>
                  </div>
                </div>
                <br><br>
              </div>
              
              {% endfor %}
                <!-- Sidebar Widgets Column -->
                
               
           
    
            </div>
            <!-- /.row -->

            <footer class="py-5 bg-dark">
                            <div class="container">
                              <p class="m-0 text-center text-white">Copyright &copy; MMBrothers App 2018</p>
                            </div>
                            <!-- /.container -->
                          </footer>
      
          </div>
          <!-- /.container -->
    

          



{% else %}

<div class="container">
    <h3>Yayınladığınız Makaleler</h3>
    <hr>
    <p>
        Hoş geldiniz, <small>{{request.user.first_name}}</small>
</p>
    <div class="col-md-3" style="float:right">
        <br><br>            
            <!-- Search Widget -->
            <div class="card my-4">
              <h5 class="card-header">Makale arayın</h5>
              <div class="card-body">
                    
                        <form class="input-group">
                                {% csrf_token %}
                                <input type="text" name="keyword" class="form-control" maxlength="10" placeholder="Ara...">
                                <button type="submit" class="btn btn-primary">Ara</button>
                            </form>   
                </div>
            </div>
             
          </div>
 

<div class="alert alert-danger">
    Makale bulunamadı.
</div>
<br><br><br><br><br><br><br>
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; MMBrothers App 2018</p>
  </div>
  <!-- /.container -->
</footer>

</div>

{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

<h3>Kontrol Paneli</h3>
<hr>
<p>
        Hoş geldiniz, <small>{{request.user.first_name}}</small>
</p>

<a class="btn btn-primary" href = "{% url 'article:addarticle' %}">Makale Ekle</a>
<hr> 
{% if articles %}
        <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Başlık</th>
                    <th scope="col">Oluşturulma Tarihi</th>
                    <th scope="col">Güncelle</th>
                    <th scope="col">Sil</th>
        
                  </tr>
                </thead>
                <tbody>
                        {% for article in articles %}
                                <tr>
                                        <th scope="row">{{article.id}}</th>
                                        <td><a href="{% url 'article:detail' article.id  %}">{{article.title}}</a></td>
                                        <td>{{article.created_date}}</td>
                                        <td><a href={% url 'article:update' article.id  %} class="btn btn-success">Güncelle</a></td>
                                        <td><a href={% url 'article:delete' article.id  %} class="btn btn-danger">Sil</a></td>
        
                                </tr>
                        {% endfor %}
                 
                </tbody>
        </table>
{% else %}
<div class="alert alert-danger">
        Henüz bir makaleniz bulunmuyor...
</div>
{% endif %}




{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}

      <!-- Page Content -->
      <div class="container">
  
        <div class="row">
  
          <!-- Post Content Column -->
          <div class="col-lg-12">
  
            <!-- Title -->
            <h1 class="mt-4">{{article.title}}</h1>
  
            <!-- Author -->
            <p class="lead">
              by
              <a href="{%url 'article:article'%}">{{article.author.username}}</a>
            </p>
  
            <hr>
  
            <!-- Date/Time -->
            <p>{{article.created_date}}'de Yayınlandı</p>
  
            <hr>
  
            <!-- Preview Image -->
            <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
  
            <hr>
  
            <!-- Post Content -->
            <p class="lead"> {{article.content|safe}} </p>

            <hr>
  
            <!-- Comments Form -->
            <div class="card my-4">
              <h5 class="card-header">Yorum Yap</h5>
              <div class="card-body">
                <form method="POST" action="{%url 'article:comment' article.id %}">
                  {% csrf_token %}
                  <div class="form-group">
                    <div class="form-group">
                          <label for="formGroupExampleInput">İsim</label>
                          <input name="comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi Girin">
                          
                        </div>
                        <label for="formGroupExampleInput">Yorumunuz</label>
                    <textarea name="comment_content" class="form-control" rows="3"></textarea>
                  </div>
                  <button type="submit" style="float:right" class="btn btn-primary">Gönder</button>
                </form>
              </div>
            </div>

            {% if comments %}
            <h5>Yorumlar</h5>
            <hr>
            {% for comment in comments %}
            <div class="media mb-4">
                <img class="d-flex mr-3 rounded-circle" src="/media/logo.png" alt="guest image">
                <div class="media-body">
                  <h5 class="mt-0">{{comment.comment_author}}</h5>
                  {{comment.comment_date}} <br>
                  {{comment.comment_content}}
                </div>
              </div>
              <hr>
            
            {% endfor %}
            

          </div>
  
          </div>
          <!-- /.row -->
    
        </div>
        <!-- /.container -->
          
    
        <!-- Footer -->
        <footer class="py-5 bg-dark">
          <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; MMBrothers App 2018</p>
          </div>
          <!-- /.container -->
        </footer>

            {% else %}
            <div class="alert alert-danger">İlk yorumu yapmak ister misin?</div>
          </div>
  
        </div>
        <!-- /.row -->
  
      </div>
      <!-- /.container -->
  
      <!-- Footer -->
      <footer class="py-5 bg-dark">
        <div class="container">
          <p class="m-0 text-center text-white">Copyright &copy; MMBrothers App 2018</p>
        </div>
        <!-- /.container -->
      </footer>

            {% endif %}
            <!-- Single Comment -->
           
  
  
         
{% endblock body %}

templates/includes/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'index' %}">MY Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'about' %}">Hakkımızda</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'article:article' %}">Makaleleriniz</a>
              </li>
            {% else %}
            {% endif %}
            
          </ul>    
          


          <ul class="navbar-nav ml-auto">
              {% if  request.user.is_authenticated %}
              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'article:dashboard' %}">Kontrol Paneli</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'user:logout' %}">Çıkış Yap</a>
                  </li>
          
              {% else %}
              
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'user:login' %}">Giriş Yap</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'user:register' %}">Kayıt Ol</a>
                  </li>
              {% endif %}
              
            </ul>    

        </div>
      </nav>
</body>
</html>

templates/includes/posttemplate.html
<div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">Post Title</h1>

          <!-- Author -->
          <p class="lead">
            by
            <a href="#">Start Bootstrap</a>
          </p>

          <hr>

          <!-- Date/Time -->
          <p>Posted on January 1, 2018 at 12:00 PM</p>

          <hr>

          <!-- Preview Image -->
          <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

          <hr>

          <!-- Post Content -->
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

          <blockquote class="blockquote">
            <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
            <footer class="blockquote-footer">Someone famous in
              <cite title="Source Title">Source Title</cite>
            </footer>
          </blockquote>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

          <hr>

          <!-- Comments Form -->
          <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
              <form>
                <div class="form-group">
                  <textarea class="form-control" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>

          <!-- Single Comment -->
          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
          </div>

          <!-- Comment with nested comments -->
          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

              <div class="media mt-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                  <h5 class="mt-0">Commenter Name</h5>
                  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
              </div>

              <div class="media mt-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                  <h5 class="mt-0">Commenter Name</h5>
                  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
              </div>

            </div>
          </div>

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">Web Design</a>
                    </li>
                    <li>
                      <a href="#">HTML</a>
                    </li>
                    <li>
                      <a href="#">Freebies</a>
                    </li>
                  </ul>
                </div>
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">JavaScript</a>
                    </li>
                    <li>
                      <a href="#">CSS</a>
                    </li>
                    <li>
                      <a href="#">Tutorials</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <!-- Side Widget -->
          <div class="card my-4">
            <h5 class="card-header">Side Widget</h5>
            <div class="card-body">
              You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
            </div>
          </div>

        </div>

      </div>

templates/index.html
{% extends "layout.html" %}
{% block body %}
                     
    
{% if articles %}

<div class="container">

    <div class="" style="float:right">
                    
            <!-- Search Widget -->
            <div class="card my-4">
              <h5 class="card-header">Makale arayın</h5>
              <div class="card-body">
                    
                        <form class="input-group">
                                {% csrf_token %}
                                <input type="text" name="keyword" class="form-control" maxlength="10" placeholder="Ara...">
                                <button type="submit" class="btn btn-primary">Ara</button>
                            </form>   
                </div>
            </div>
          </div>
  
    <div class="row"> 

{% for article in articles %}
    <!-- Page Content -->
  
    
      
              <!-- Blog Entries Column -->
              <div class="col-md-12">
      
                <!-- Blog Post -->
                <div class="card mb-4">
                  <img class="card-img-top" src="{{article.article_image.url}}" alt="">
                  <div class="card-body">
                   <a href="{% url 'article:detail' article.id  %}"><h2 class="card-title">{{article.title}}</h2></a> 
                    <p class="card-text">{{article.content|safe|truncatewords:50}}</p>
                    <a href="{% url 'article:detail' article.id  %}" class="btn btn-primary" style="float:right">Devamını Oku &rarr;</a>
                  </div>
                  <div class="card-footer text-muted">
                    <p>{{article.author.username}} tarafından  {{article.created_date}}'da oluşturuldu.</p>
                  </div>
                </div>
                <br><br>
              </div>
              
              {% endfor %}
                <!-- Sidebar Widgets Column -->
                
               
           
    
            </div>
            <!-- /.row -->

            <footer class="py-5 bg-dark">
                            <div class="container">
                              <p class="m-0 text-center text-white">Copyright &copy; MMBrothers App 2018</p>
                            </div>
                            <!-- /.container -->
                          </footer>
      
          </div>
          <!-- /.container -->
    

          



{% else %}

<div class="container">
    <h3>Makaleler</h3>
    <hr>
    <div class="col-md-3" style="float:right">
        <br><br>            
            <!-- Search Widget -->
            <div class="card my-4">
              <h5 class="card-header">Makale arayın</h5>
              <div class="card-body">
                    
                        <form class="input-group">
                                {% csrf_token %}
                                <input type="text" name="keyword" class="form-control" maxlength="10" placeholder="Ara...">
                                <button type="submit" class="btn btn-primary">Ara</button>
                            </form>   
                </div>
            </div>
             
          </div>
 

<div class="alert alert-danger">
    Makale bulunamadı.
</div>
<br><br><br><br><br><br><br>
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; MMBrothers App 2018</p>
  </div>
  <!-- /.container -->
</footer>

</div>

{% endif %}

{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link href="css/blog-home.css" rel="stylesheet">
</head>
<body>
    
   {% include "includes/navbar.html" %}

  

    <div style ="margin-top: 100px; margin-bottom: 100px;" class="container">
        {% if messages %}
            {% for message in messages %}
            {% if message.tags == "warning" %}
            <div class="alert alert-danger">{{ message }}</div>
            {% else %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endif %}
            {% endfor %}
        
        {% endif %}
        
        {% block body %}
        
        {% endblock body %}

    </div>

    <script src="{% static  'js/bootstrap.min.js' %}"></script>
    <script src="{% static  'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static  'js/run_prettify.js' %}"></script>

</body>
</html>

templates/update.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Güncelle</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-success">Güncelle</button>
        </form>
    </div>
</div>

{% endblock body %}